//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011
//http://www.mikroe.com

//GLCD FontName : NumberFont3x5
//GLCD FontSize : 3 x 5

static const uint8_t NumberFont3x5[] PROGMEM = {
  0x0, 0x0,  // size of zero indicates fixed width font, actual length is width * height
  0x03,      // width
  0x05,      // height
  0x30,      // first char
  0x10,      // char count

  0x1F, 0x11, 0x1F,  // Code for char 0
  0x11, 0x1F, 0x10,  // Code for char 1
  0x1D, 0x15, 0x16,  // Code for char 2
  0x15, 0x15, 0x1E,  // Code for char 3
  0x07, 0x04, 0x1E,  // Code for char 4
  0x17, 0x15, 0x19,  // Code for char 5
  0x1F, 0x14, 0x1C,  // Code for char 6
  0x01, 0x1D, 0x03,  // Code for char 7
  0x1F, 0x15, 0x1F,  // Code for char 8
  0x07, 0x05, 0x1F   // Code for char 9
};
