; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	freetronics/DMD2@^0.0.4
	gmarty2000/Buzzer@^1.0.0
	thijse/EEPROMEx@0.0.0-alpha+sha.09d7586108
	apechinsky/MemoryFree@^0.3.0
	einararnason/ArduinoQueue@^1.2.5
	charlesbaynham/OSFS@^1.2.3
	bblanchon/ArduinoJson@^7.3.0
	greiman/SdFat@^2.3.0
	mattfryer/Board Identify@^0.2
